version: 2
sources:
  - name: RAW
    description: This is RAW_TEST Database Source Tables used for STAGE Layer
    database: DBTTRAINING
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
  - name: STAGE
    description: This is STAGE Database Source Tables used for PUBLISH
    database: DBTTRAINING
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION